import {
  Container,
  Heading,
  Text,
  VStack,
  HStack,
  Box,
  Image,
  Wrap,
  WrapItem,
  Center,
  Grid,
  GridItem,
  extendTheme,
} from "@chakra-ui/react";
import Head from "next/head";

// import Image from "next/image";

import Navbar from "../components/nav";
import Search from "../components/searchBar";

const breakpoints = {
  sm: "320px",
  md: "768px",
  lg: "960px",
  xl: "1200px",
  "2xl": "1536px",
};

const theme = extendTheme({ breakpoints });

export default function Home() {
  return (
    <div>
      <Head>
        <title>Nutrition</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/BlogLogo.png" />
      </Head>
      <Navbar />
      <VStack
        align="stretch"
        p="2rem"
        bg="linear-gradient(to top right, #99ccff 0%, #009933 100%)"
      >
        <Container maxW="4xl">
          <HStack>
            <Text
              fontSize={{
                base: "20px",
                sm: "25px",
                md: "25px",
                xl: "35px",
                "2xl": "45px",
              }}
            >
              {
                "When Diet is Wrong, Medicine is of no use. When Diet is right Medicine is of no need. -Ayurveda"
              }
            </Text>
            <Box width={{ base: "100%", sm: "50%", md: "25%" }}>
              <Image src="/yoga.svg" alt="Yoga Illustration" />
            </Box>
          </HStack>
        </Container>
        <Center>
          <Search />
        </Center>
      </VStack>
      <Center>
        <Heading pt="1rem">How to use!</Heading>
      </Center>

      <Container maxW="4xl">
        <Grid templateColumns="repeat(2,1fr)">
          <GridItem>
            <Image
              boxSize={{
                base: "200px",
                sm: "250px",
                md: "350px",
                xl: "370px",
                "2xl": "370px",
              }}
              src="/diet.svg"
              alt="Diet Illustration"
            />
          </GridItem>
          <GridItem>
            <Container pt="2rem" pb="4rem">
              <Text
                fontSize={{
                  base: "20px",
                  sm: "20px",
                  md: "20px",
                  xl: "25px",
                  "2xl": "30px",
                }}
              >
                Nutrition is very important in daily life. But it can be hard to
                keep track of such things. You can now search for the Nutrition
                value of your food with just one search!
              </Text>
              <Text
                fontSize={{
                  base: "20px",
                  sm: "20px",
                  md: "20px",
                  xl: "25px",
                  "2xl": "30px",
                }}
              >
                In the search field first write the quantity of your food.
                Followed by the name of the food you want a search for.
              </Text>
            </Container>
          </GridItem>
        </Grid>
      </Container>
    </div>
  );
}
